INSERT INTO meals VALUES (0,'Breakfast', '', 'Top 25g of low-fat Greek yoghurt with two chopped apricots', '', 68);
INSERT INTO meals VALUES (0,'Lunch', '', 'Tesco’s Broccoli and Stilton soup is a great option as you can still get a cheese fix', '', 160);
INSERT INTO meals VALUES (0,'Dinner', '', 'A serving of this sausage dinner with roasted ratatouille is one for all of the family will enjoy', 'http://www.womanmagazine.co.uk/food/sausages-with-roasted-ratatouille/', 262);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Give a slice of white bread a kick – toast it and top with half a teaspoon of cinnamon', '', 91);
INSERT INTO meals VALUES (0,'Lunch', '', 'Mushroom soup keeps lunch healthy and Knorr’s version means you’ll have more calories to use up for snacks', '', 106.);
INSERT INTO meals VALUES (0,'Dinner', '', 'Fusilli makes this American dream pasta salad super filling.', 'http://www.womanmagazine.co.uk/food/american-dream-pasta-salad-recipe/', '210');
INSERT INTO meals VALUES (0,'Breakfast', '', 'Using egg whites for an omelette is a great way to cut calories. Use 3 egg whites, 80g mushrooms and 80g spinach.', '', 60);
INSERT INTO meals VALUES (0,'Lunch', '', 'You can afford to treat yourself, as Sainsbury’s tabbouleh salad is indulgent but still low-cal.', '', 147);
INSERT INTO meals VALUES (0,'Dinner', '', 'This sizzling chicken and cashew stir-fry beats a takeaway.', 'http://www.womanmagazine.co.uk/food/sizzling-chicken-and-cashew-stir-fry-recipe/', 257);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Start the day with a fruit medley of 1 kiwi, 1 medium satsuma and 25g low-fat Greek yoghurt.', '', 101);
INSERT INTO meals VALUES (0,'Lunch', '', 'Go green with this crunchy three bean salad.', '', 131);
INSERT INTO meals VALUES (0,'Dinner', '', 'Speedy and super low in calories', 'http://www.womanmagazine.co.uk/food/speedy-chicken-thighs-and-roasted-vegetables/', 177);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Kickstart your day with a banana', '', 90);
INSERT INTO meals VALUES (0,'Lunch', '', 'Pick up a Beetroot and Cheese Salad from Waitrose for the ultimate crispy and chunky fix.', '', 172);
INSERT INTO meals VALUES (0,'Dinner', '', 'This super-easy chicken tikka masala is also surprisingly good for you – and with a mini nan you can get your carb fix too!', 'http://www.womanmagazine.co.uk/food/super-easy-chicken-tikka-masala/', 200);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Start off the day with a hard-boiled egg', '', 78);
INSERT INTO meals VALUES (0,'Lunch', '', 'Take half of Weight Watcher’s Mediterranean Veg Quiche', '', 156);
INSERT INTO meals VALUES (0,'Dinner', '', 'Soup for dinner might not sound very filling, but this lovely leek version, served with yummy cheese toasts will definitely you leave you feeling full – perfect!', 'http://www.womanmagazine.co.uk/food/lovely-leek-soup-with-mini-cheesy-toasts/', 200);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Blend ½ banana, 6oz semi-skimmed milk, 1tsp vanilla extract, 1tsp cinnamon and 1/3 cup of crushed ice for a delicious banana milkshake', '', 128);
INSERT INTO meals VALUES (0,'Lunch', '', 'Half of Sainsbury’s Creamy Vegetable Soup is a super healthy option. Add a rice cake to the lunch menu to make it that little more filling.', '', 88);
INSERT INTO meals VALUES (0,'Dinner', '', 'Warming, chunky, delicious and easy – what’s not to love about this beef stew?', 'http://www.womanmagazine.co.uk/food/recipe-of-the-day-rich-beef-stew/', 240);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Perfect to grab on the go, an Alpen Fruit and Nut Bar starts your day off.', '', 109);
INSERT INTO meals VALUES (0,'Lunch', '', 'Make your midday meal a filling one with a slice of toasted rye bread with a small can of reduced sugar and salt baked beans.', '', 195);
INSERT INTO meals VALUES (0,'Dinner', '', 'Forget a Thai takeaway and try this fiery prawn tom yam soup instead. It’s your better option by a mile!', 'http://www.womanmagazine.co.uk/food/lemony-chicken-vegetable-couscous/', 172);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Chocolate for brekkie isn’t as awful as it sounds; try a Tesco white chocolate and strawberry cereal bar', '', 85);
INSERT INTO meals VALUES (0,'Lunch', '', 'Pack a fiery punch at lunchtime with Tesco’s Chilli Chicken Noodle Salad', '', 195);
INSERT INTO meals VALUES (0,'Dinner', '', 'Curries aren’t completely off the menu if you’re trying to be good as this veggie balti curry is just 211 calories.', 'http://www.womanmagazine.co.uk/food/veggie-balti-curry-recipe/', 211);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Start the day off to a warming start with a sachet of Tesco’s Micro Oats.', '', 105);
INSERT INTO meals VALUES (0,'Lunch', '', 'You can’t beat a classic tomato soup, and Heinz’s Cream of Tomato Reduced Salt comes in at a light 115 calories.','',115);
INSERT INTO meals VALUES (0,'Dinner', '', 'These zesty pork skewers are tender and filling and a great choice', 'http://www.womanmagazine.co.uk/food/zesty-pork-skewers-recipe/', 201);
INSERT INTO meals VALUES (0,'Breakfast', '', 'A banana is ideal for breakfast on the go and will give you plenty of energy for the rest of the day', '', 90);
INSERT INTO meals VALUES (0,'Lunch', '', 'Low calorie foods don’t have to be boring. Pop to Prêt and grab a Simple Tuna Salad', '', 170);
INSERT INTO meals VALUES (0,'Dinner', '', 'Try whipping up a low cal lemony chicken with vegetable couscous', 'http://www.womanmagazine.co.uk/food/lemony-chicken-vegetable-couscous/', 238);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Start the day off with a Muller Light Strawberry yoghurt', '', 89);
INSERT INTO meals VALUES (0,'Lunch', '', 'Heinz Weight Watchers Tomato Soup is just 76cals, and if you need a bit more filling up try munching on two rice cakes', '', 146);
INSERT INTO meals VALUES (0,'Dinner', '', 'Low calorie doesn’t mean tasteless! We love these low fat spiced lamb skewers', 'http://www.womanmagazine.co.uk/food/low-fat-spiced-lamb-skewers/', 239);
INSERT INTO meals VALUES (0,'Breakfast', '', 'For a sweet fix try having one crumpet with a teaspoon of honey and 20 raspberries', '', 120);
INSERT INTO meals VALUES (0,'Lunch', '', 'Enjoy a Love Life You Count Tamarind Duck Lettuce Wrap from Waitrose', '', 86);
INSERT INTO meals VALUES (0,'Dinner', '', 'This roasted cod recipe is the perfect healthy, filling dinner.', 'http://www.womanmagazine.co.uk/food/roasted-cod-parma-ha-peppers-recipe/', 224);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Melba toast is great when you’re on a diet. Try having two pieces of Melba toast each covered in one tablespoon of Philadelphia Light & Healthy Cream Cheese', '', 96);
INSERT INTO meals VALUES (0,'Lunch', '', 'One mini Quorn Sausage Roll (48cals) will stop you from missing comfort foods. Serve with a salad made up of 30grams of spinach (7cals), 4 cherry tomatoes (16 cals) and a medium cucumber (24cals).', '', 95);
INSERT INTO meals VALUES (0,'Dinner', '', 'This prawn and potato curry will only take 30 minutes to make, and it’s well within the 500 calorie plan!', 'http://www.womanmagazine.co.uk/food/prawn-potato-curry-recipe/', 266);
INSERT INTO meals VALUES (0,'Breakfast', '', 'A medley of a banana (90cals), 25 blueberries (20cals) and a kiwi (46cals) will give you a fruity start to the day.', '', 156);
INSERT INTO meals VALUES (0,'Lunch', '', 'Young’s Cod Steak in Parsley Sauce (101cals) is perfect for fasting days. Eat it on a bed of 30grams of lettuce (4cals).', '', 105);
INSERT INTO meals VALUES (0,'Dinner', '', 'Try our hunger-busting veggie balti to fight off the fasting blues!', 'http://www.womanmagazine.co.uk/food/veggie-balti-curry-recipe/', 211);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Start off the day with an omelette with two eggs, 50grams of red pepper and 50grams of onion', '', 156);
INSERT INTO meals VALUES (0,'Lunch', '', 'A sachet of miso soup (14cals) will warm you up, and try snacking on two carrot sticks (50cals).', '', 64);
INSERT INTO meals VALUES (0,'Dinner', '', 'Lean meats are perfect for a low calorie diet. Try a small sirloin steak with 200grams of mixed lettuce salad. Drizzle with some lemon for extra flavour', '', 275);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Blend 100grams of fresh strawberries with 150ml skimmed milk for a breakfast milkshake (95cals) and make sure you’re full by eating one tangerine too (25cals)', '', 120);
INSERT INTO meals VALUES (0,'Lunch', '', 'Home made tomato and lentil soup is super easy to make. Simply use 150grams of red lentils, vegetable stock, garlic, ginger and spices and one can of tinned tomatoes. This will make four servings so you don’t need to worry about lunch on fasting days for a while!', '', 123);
INSERT INTO meals VALUES (0,'Dinner', '', 'A quick and easy veggie spaghetti is perfect after a long day!', 'http://www.womanmagazine.co.uk/food/veggie-spaghetti-recipe/', 240);
INSERT INTO meals VALUES (0,'Breakfast', '', 'Try starting off the day with a hard-boiled egg (78cals).', '', 78);
INSERT INTO meals VALUES (0,'Lunch', '', 'If you’re craving carbs, have a small jacket potato topped with 50grams of cottage cheese', '', 198);
INSERT INTO meals VALUES (0,'Dinner', '', 'This roasted vegetable and cous cous salad will fill you up in the evening, and gives you enough spare calories for a sweet treat! Try swapping pudding for one Walls Mini Milk (30cals).', 'http://www.womanmagazine.co.uk/food/roasted-vegetable-cous-cous/', 160);
INSERT INTO meals VALUES (0,'Breakfast', '', 'A 100gram serving of Onken’s fat free raspberry and honey yoghurt will give you a sweet start to the day.', '', 79);
INSERT INTO meals VALUES (0,'Snack', '', 'A serving of Saitaku Miso Soup will leave you enough calories for a mid-morning or mid-afternoon snack.', '', 14);
INSERT INTO meals VALUES (0,'Dinner', '', 'A veggie kebab will make dinner time a little more exciting!', 'http://www.womanmagazine.co.uk/food/veggie-kebabs-recipe/', 282);
INSERT INTO meals VALUES (0,'Breakfast', '', 'A 36gram serving of Quaker’s porridge made with 180ml skimmed milk will keep you going throughout the day.', '', 216);
INSERT INTO meals VALUES (0,'Lunch', '', 'You can still enjoy small treats on fasting days! Try having one McCain oven baked pizza finger (78cals) with a side of Tesco’s green side salad (12cals). If you need a sweet fix, have one party ring (29cals)', '', 119);
INSERT INTO meals VALUES (0,'Dinner', '', 'Sticking to 500 calories is a great way to get in your 5 a day. Try this Mediterranean vegetable stew for a healthy end to the day.', 'http://www.womanmagazine.co.uk/food/mediterranean-vegetable-stew-recipe/', 150);
INSERT INTO meals VALUES (0,'Snack', '', 'For a sweet afternoon treat, have a Jaffa cake', '', 90);
INSERT INTO meals VALUES (0,'Snack', '', 'Snack on 50g of blueberries in the afternoon', '', 28);
INSERT INTO meals VALUES (0,'Snack', '', 'Snack on a packet of Weight Watchers salt and vinegar Crinkle Crisps in the afternoon', '', 78);
INSERT INTO meals VALUES (0,'Snack', '', 'If you fancy a mid-morning treat, opt for a Ritz cracker at 17 calories each.', '', 17);
INSERT INTO meals VALUES (0,'Snack', '', 'Try a satsuma as an elevenses snack.', '', 25);
INSERT INTO meals VALUES (0,'Snack', '', 'Try a Tesco side salad to give you an energy-boost', '', 12);
INSERT INTO meals VALUES (0,'Snack', '', 'Top up your fruit fix with a tangerine to keep you going until lunch', '', 24);
INSERT INTO meals VALUES (0,'Snack', '', 'Try a rice cake', '', 35);
INSERT INTO meals VALUES (0,'Snack', '', 'To keep you going until lunchtime, have a Tuc cracker as a mid-morning snack', '', 24);
INSERT INTO meals VALUES (0,'Snack', '', 'If you fancy a mid-morning snack, opt for a fruity Weight Watchers citrus yoghurt', '', 60);
INSERT INTO meals VALUES (0,'Snack', '', 'Try 25 blueberries', '', 20);
INSERT INTO meals VALUES (0,'Snack', '', 'Snack on a pear', '', 36);
INSERT INTO meals VALUES (0,'Snack', '', 'If you’re missing crisps, try snacking on a packet of Walkers salt and vinegar French Fries', '', 97);
